### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by stokito** [stokito/IdeaJol#20]
```
In file: BaseSubscriberAttributes.java

java.lang.NullPointerException
	at org.openjdk.jol.info.ClassData.fieldsFor(ClassData.java:254)
	at org.openjdk.jol.info.ClassData.ownFields(ClassData.java:222)
	at org.openjdk.jol.layouters.HotSpotLayouter.layout(HotSpotLayouter.java:138)
	at com.github.stokito.IdeaJol.inspection.JolInspection.checkClass(JolInspection.java:48)
	at com.intellij.codeInspection.AbstractBaseJavaLocalInspectionTool$1.visitClass(AbstractBaseJavaLocalInspectionTool.java:60)
	at com.intellij.psi.JavaElementVisitor.visitTypeParameter(JavaElementVisitor.java:339)
	at com.intellij.psi.impl.source.tree.java.PsiTypeParameterImpl.accept(PsiTypeParameterImpl.java:347)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:321)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
```

**Comment by stokito** [comment]
today I saw the same exception and it looks like it occurred when we set a JDK for the project.
This is hard to repdoduce

**Comment by volyx** [comment]
+1

Trace
```
java.lang.AssertionError
	at org.openjdk.jol.info.ClassData.fieldsFor(ClassData.java:249)
	at org.openjdk.jol.info.ClassData.ownFields(ClassData.java:221)
	at org.openjdk.jol.layouters.HotSpotLayouter.layout(HotSpotLayouter.java:138)
	at com.github.stokito.IdeaJol.inspection.JolInspection.checkClass(JolInspection.java:50)
	at com.intellij.codeInspection.AbstractBaseUastLocalInspectionTool$1.visitClass(AbstractBaseUastLocalInspectionTool.java:75)
	at org.jetbrains.uast.UClass$DefaultImpls.accept(UClass.kt:71)
	at org.jetbrains.uast.java.AbstractJavaUClass.accept(JavaUClass.kt:23)
	at com.intellij.uast.UastHintedVisitorAdapter.visitElement(UastHintedVisitorAdapter.kt:21)
	at com.intellij.psi.impl.source.tree.java.PsiTypeParameterImpl.accept(PsiTypeParameterImpl.java:350)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by FantasticMao** [comment]
+1
Intellij IDEA 2018.3.6
![image](https://user-images.githubusercontent.com/20675747/69913333-7846fe80-1471-11ea-91f9-3e0c5108781b.png)

**Comment by stokito** [comment]
The issue is because sometimes PsiClass.getQualifiedName() returns null.

I was able to reproduce the problem on Hibernate sources. I made `Analyze` / `Run inspection by name` / `JOL: Class has too big memory footprint` and watched which classes produces the NPE on analyze:

`org.hibernate.jpamodelgen.test.mappedsuperclass.typedmappedsuperclass.AttachmentGroup`
In the class for some reason the generic type `GroupType` is a superclass for the PsiClass of `AttachmentGroup`.
This looks strange for me but I tried to determine that the superclass is generic and exclude it but this looks too complicated.

Another NPE occurred with inline class `IntegratorObserver` in `org/hibernate/internal/SessionFactoryImpl.java:261`.  And I wasn't able to figure out why.

For now I can't fix it but I made some workaround just to ignore such classes.
I uploaded the patched version (as a bonus I also updated JOL dependency) so in few days please update the plugin.

The issue will remain opened for a better times
Closes #22
