### ISSUE TITLE
IDE freeze with invalid source code causing superclass recursion

### ISSUE THREAD

**Issue by Firestar99** [stokito/IdeaJol#32]
Complete IDE freeze when typing source code and a "superclass recursion" is typed (see example below) and one would right-click -> Show Object Layout. Happened while testing for #29. However as it is invalid source code and noone would actually do this action anyway feel free to just ignore :)
```
class Buffer extends Buffer {

}
```

Thread dump (partially):
```Java
"AWT-EventQueue-0" #30 prio=6 os_prio=0 cpu=42602.66ms elapsed=173.77s tid=0x00007fe06c11a000 nid=0x8c45 runnable  [0x00007fe02c7c0000]
   java.lang.Thread.State: RUNNABLE
        at com.intellij.reference.SoftReference.deref(SoftReference.java:56)
        at com.intellij.psi.impl.source.FileTrees.derefTreeElement(FileTrees.java:71)
        at com.intellij.psi.impl.source.PsiFileImpl.derefTreeElement(PsiFileImpl.java:115)
        at com.intellij.psi.impl.source.PsiFileImpl.getTreeElement(PsiFileImpl.java:104)
        at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:618)
        at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:952)
        at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:39)
        at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:352)
        at com.intellij.psi.impl.source.PsiClassImpl.isInterface(PsiClassImpl.java:415)
        at com.intellij.psi.impl.PsiClassImplUtil.getSuperClass(PsiClassImplUtil.java:692)
        at com.intellij.psi.impl.source.PsiClassImpl.getSuperClass(PsiClassImpl.java:200)
        at com.github.stokito.IdeaJol.PsiClassAdapter.addClassFields(PsiClassAdapter.java:41)
        at com.github.stokito.IdeaJol.PsiClassAdapter.createClassDataFromPsiClass(PsiClassAdapter.java:23)
        at com.github.stokito.IdeaJol.toolwindow.JolView.calcClassLayout(JolView.java:242)
        at com.github.stokito.IdeaJol.toolwindow.JolView.showLayoutForSelectedClass(JolView.java:93)
        at com.github.stokito.IdeaJol.toolwindow.JolView.showLayoutForClass(JolView.java:79)
        at com.github.stokito.IdeaJol.toolwindow.JolView.showJolToolWindow(JolView.java:253)
        at com.github.stokito.IdeaJol.ShowObjectLayoutAction.actionPerformed(ShowObjectLayoutAction.java:33)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$3019/0x0000000102141040.run(Unknown Source)
        at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
        at com.intellij.util.SlowOperations$$Lambda$1508/0x00000001015f7840.compute(Unknown Source)
        at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
        at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$$Lambda$5464/0x00000001030c6440.run(Unknown Source)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
        at javax.swing.AbstractButton.fireActionPerformed(java.desktop@11.0.11/AbstractButton.java:1967)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$$Lambda$5461/0x00000001030c7840.run(Unknown Source)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:515)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:545)
        at java.awt.Component.processMouseEvent(java.desktop@11.0.11/Component.java:6652)
        at javax.swing.JComponent.processMouseEvent(java.desktop@11.0.11/JComponent.java:3345)
        at java.awt.Component.processEvent(java.desktop@11.0.11/Component.java:6417)
        at java.awt.Container.processEvent(java.desktop@11.0.11/Container.java:2263)
        at java.awt.Component.dispatchEventImpl(java.desktop@11.0.11/Component.java:5027)
        at java.awt.Container.dispatchEventImpl(java.desktop@11.0.11/Container.java:2321)
        at java.awt.Component.dispatchEvent(java.desktop@11.0.11/Component.java:4859)
        at java.awt.LightweightDispatcher.retargetMouseEvent(java.desktop@11.0.11/Container.java:4918)
        at java.awt.LightweightDispatcher.processMouseEvent(java.desktop@11.0.11/Container.java:4547)
        at java.awt.LightweightDispatcher.dispatchEvent(java.desktop@11.0.11/Container.java:4488)
        at java.awt.Container.dispatchEventImpl(java.desktop@11.0.11/Container.java:2307)
        at java.awt.Window.dispatchEventImpl(java.desktop@11.0.11/Window.java:2784)
        at java.awt.Component.dispatchEvent(java.desktop@11.0.11/Component.java:4859)
        at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.11/EventQueue.java:778)
        at java.awt.EventQueue$4.run(java.desktop@11.0.11/EventQueue.java:727)
        at java.awt.EventQueue$4.run(java.desktop@11.0.11/EventQueue.java:721)
        at java.security.AccessController.doPrivileged(java.base@11.0.11/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.11/ProtectionDomain.java:85)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.11/ProtectionDomain.java:95)
        at java.awt.EventQueue$5.run(java.desktop@11.0.11/EventQueue.java:751)
        at java.awt.EventQueue$5.run(java.desktop@11.0.11/EventQueue.java:749)
        at java.security.AccessController.doPrivileged(java.base@11.0.11/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.11/ProtectionDomain.java:85)
        at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.11/EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
        at com.intellij.ide.IdeEventQueue$$Lambda$417/0x00000001006b3c40.compute(Unknown Source)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
        at com.intellij.ide.IdeEventQueue$$Lambda$416/0x00000001006b4c40.run(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.11/EventDispatchThread.java:203)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.11/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.11/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.11/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.11/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@11.0.11/EventDispatchThread.java:90)

   Locked ownable synchronizers:
        - None

```

**Comment by stokito** [comment]
thank you for the report, I don't think it worth to fix it due to low possibility of the bug. I'll leave this ticket open and maybe someday I'll fix it
