### ISSUE TITLE
'com.github.stokito.IdeaJol.ShowObjectLayoutAction' must override `getActionUpdateThread` and chose EDT or BGT. BGT is prefferable

### ISSUE THREAD

**Issue by maxmedvedev** [stokito/IdeaJol#43]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.stokito.IdeaJol.ShowObjectLayoutAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: JOL]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:198)
```

**Comment by maxmedvedev** [comment]
Just in case, ping me you need help or you're ready to accept my pull request

**Comment by stokito** [comment]
thank you for the reporting. I can accept a PR but anyway I'll need a time to make a release.
Hope I'll do it before it breaks.
